---

- name: "Apache installation"
  hosts: all
  tasks:
    - name: "Install package apache"
      yum:
        name: "httpd"
        state: "present"
    - name: "Start apache service"
      service:
        name: "httpd"
        state: "started"
        enabled: yes
    - name: "Allow http connections"
      firewalld:
        service: "http"
        permanent: yes
        state: enabled
    - name: "Copy test.html"
      copy:
        src: "test.html"
        dest: "/var/www/html"
        owner: "apache"
        group: "apache"
