---

- name: "Table count"
  hosts: mysql
  gather_facts: no
  tasks:
    - name: "Retrieve table count"
      mysql_request:
        db_name: "mediawiki"
        request: "{{lookup('file', 'test.sql')}}"
    - debug: var=mysql_results
