kind: Service
apiVersion: v1
metadata:
  name: 'keycloak'
  namespace: 'default'
spec:
  ports:
    - name: "http"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: 'keycloak'
  type: ClusterIP
