---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
