---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  collections:
    - ansible.builtin
  tasks:
  - name: "Retrieve package list"
    package_facts: {}
  - name: "Retrieve services state"
    service_facts: {}
  - name: "Check Apache package"
    assert:
      that: packages.httpd
  - name: "Check assertion on service status"
    assert:
      that:
        - services["httpd.service"].state  == "running"
        - services["httpd.service"].status == "enabled"
