---

- name: "remi repo activation"
  hosts: apache
  gather_facts: no
  tasks:
    - name: "epel activation"
      yum:
        name: "epel-release"
        state: present
    - name: "remi repo activation"
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present
    - name: "install php70 packages"
      yum:
        name: "php,php-mysql,php-xml"
        state: "latest"
        enablerepo: "remi-php70"
