---

- name: "epel activation"
  dnf:
    name: "epel-release,epel-next-release"
    enablerepo: powertools

- name: "remi repo activation"
  dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present
    disable_gpg_check: true

- name: "Import GPG Key"
  rpm_key:
    state: present
    key: "/etc/pki/rpm-gpg/{{ item }}"
  loop: ["RPM-GPG-KEY-remi", "RPM-GPG-KEY-remi2020", "RPM-GPG-KEY-remi2021", "RPM-GPG-KEY-remi2022"]

- name: "install php82 packages"
  dnf:
    name: "php82-php,php82-php-mysqlnd,php82-php-xml,php82-php-mbstring,php82-php-gd,php82-php-intl"
    state: present
    enablerepo: "remi-8.2"
  changed_when: yes
  # We need to restart apache
  notify: [ "apache restart" ]
