---

- name: "Build docker images"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Build centos-httpd image"
      docker_image:
        name: "centos-httpd"
        source: build
        force_source: yes
        build:
          path: "centos-httpd"
          pull: yes
