---

- name: "Create docker network"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Create docker network"
      docker_network:
        name: "{{network_name}}"
        state: present

- name: "Create docker plateform"
  hosts: [ "all" ]
  gather_facts: no
  tasks:
    - name: "Create containers"
      docker_container:
        name:         "{{inventory_hostname}}"
        hostname:     "{{inventory_hostname}}"
        command:      "{{start_cmd|d('/sbin/init')}}"
        networks:
          - name:     "{{network_name}}"
        image:        "{{docker_image|d('centos')}}"
        tmpfs:        ["/run", "/tmp"]
        volumes:      ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]
        privileged:   "{{ privileged|d(False) }}"
        state:        started
      delegate_to: localhost
