---

- name: "Create podman network"
  hosts: localhost
  gather_facts: no
  collections: &collections
    - "containers.podman"
  tasks:
    - name: "Create podman network"
      podman_network:
        name: "{{ network_name }}"
        state: present

- name: "Create Apache"
  hosts: [ "apache" ]
  gather_facts: no
  collections: &collections
  tasks:
    - name: "Create Apache containers"
      podman_container: &container
        name:         "{{ inventory_hostname }}"
        hostname:     "{{ inventory_hostname }}"
        network:      "{{ network_name }}"
        image:        "{{ container_image|d('quay.io/centos/centos:stream8') }}"
        state:        started
      delegate_to: localhost

- name: "Create podman plateform"
  hosts: [ "all", "!apache" ]
  gather_facts: no
  tasks:
    - name: "Create containers"
      podman_container:
        <<: *container
        command:      "/sbin/init"
      delegate_to: localhost

- name: "Install prereq"
  hosts: [ "all", "!apache", "haproxy" ]
  gather_facts: no
  tasks:
    - name: "Install prereq"
      dnf:
        name: "sudo,firewalld"
        state: present
