---

- name: "Create Proxy"
  hosts: [ "localhost" ]
  gather_facts: no
  collections:
    - "containers.podman"
  tasks:
    - name: "Launch proxy"
      podman_container: &container
        name:     "proxy"
        ports:    "3128:3128"
        network:  "{{ network_name }}"
        image:    "docker.io/mpreu/squid:5.5"
        state:    started
