---

- name: "Delete containers"
  hosts: [ "all" ]
  gather_facts: no
  tasks:
    - name: "Delete containers"
      containers.podman.podman_container:
        name:       "{{ inventory_hostname }}"
        state:      absent
      delegate_to: localhost
