---

- name: "mariadb-server installation"
  yum:
    name:  "mariadb-server,python3-PyMySQL"
    state: "installed"

- name: "start mariadb service"
  service:
    name:  "mariadb"
    state: "started"
    enabled: yes

- name: "Allow mariadb connections"
  firewalld:
    service: "mysql"
    permanent: yes
    state: enabled
